#databases configuration here!
db:
    default: "connection1"

    # connections list
    connections:

        # Example with mysql
        - connection1:
            #package
            package: "sequelize"
            #data base
            data-base:	"YOUR DATABASE"
            #user
            user:	"YOUR USER"
            #pass
            pass:	"YOUR PASS"
            #host
            host:	"DEFAULT HOST"
            #sequalize dialect
            dialect:	"mysql"
            #driver
            driver: "mysql"
            #default timezone Database
            timezone:	"America/Bogota"



        # Example with mongodb
        - connection2:
            package: "mongorito"
            data-base:	"YOUR DATABASE"
            user:	""
            pass:	""
            host:	"DEFAULT HOST"
            #mongodb port
            port:	27017